name: My Workflow
on:
  pull_request:
    types: [opened]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Pull Request Title and Number
        run: |
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"