name: Pull Request Workflow
run-name: ${{ github.actor }} Pull Request Workflow.
on:
  pull_request:
    types:
      - closed
      - opened
jobs:
  if_opened:
    runs-on: ubuntu-latest
    steps:
      - name: Print Pull request title and number.
      - uses: actions/checkout@v3
      - run: |
          echo "PR Number : ${{ github.event.pull_request.number }}"
          echo "PR Number : ${{ github.event.pull_request.number }}"
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo The PR was merged
